### ISSUE TITLE
Used to work with CM12 (AOSP 5.0.2), but doesn't anymore with CM12.1 (AOSP 5.1.1)

### ISSUE THREAD

**Issue by ghost** [riul88/call-recorder-for-android#20]
Title says it all!

My device is Serranoltexx (Samsung S4 Mini LTE European)

I won't be able to provide more info for now, since my phone keeps rebooting with this latest version.

So this is basically a FYI ;-)

**Comment by xasuyu** [comment]
Yes, same problem here.
It is because of a runtime exception.

D/Call recorder: (10386): RecordService onStartCommand
D/Call recorder: (10386): RecordService STATE_CALL_END
D/Call recorder: (10386): RecordService stopAndReleaseRecorder
D/AudioStreamInALSA(  227): read:: mParent->mIncallMode=16
D/ALSADevice(  227): route: devices 0x4000000 in mode 2
D/ALSADevice(  227): No valid output device: 0
D/alsa_ucm(  227): snd_use_case_set(): uc_mgr 0xb70773e0 identifier _enadev value DMIC Endfire
D/alsa_ucm(  227): Set mixer controls for Voice Call enable 1
D/alsa_ucm(  227): Setting mixer control: PRI_RX_Voice Mixer CSVoice, value: 1
I/InCall  ( 9737): CallList - onUpdate - [Call_1, DISCONNECTING, [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MERGE_CONFERENCE CAPABILITY_MUTE], children:[], parent:null, videoState:0, mIsActivSub:false, callSubState:0, mSessionModificationState:0, conferenceable:[], VideoSettings:(CameraDir:-1)]
I/InCall  ( 9737): InCallPresenter - Phone switching state: INCALL -> INCALL
D/MPEG4Writer(  227): Audio track stopping
D/MPEG4Writer(  227): Audio track source stopping
I/MediaCodecSource(  227): encoder (audio) stopping
E/MPEG4Writer(  227): The number of recorded samples is 0
D/alsa_ucm(  227): Setting mixer control: Voice_Tx Mixer PRI_TX_Voice, value: 1
D/ALSADevice(  227): switchDevice: mCurTxUCMDevivce DMIC Endfire mCurRxDevDevice Voice Earpiece
D/alsa_ucm(  227): snd_use_case_set(): uc_mgr 0xb70773e0 identifier _enamod value \BC\B5
E/alsa_ucm(  227): Invalid modifier identifier value
D/ALSADevice(  227): close: handle 0xb712f378 h 0x0
D/ALSADevice(  227): open: handle 0xb712f378, format 0x2
E/alsa_ucm(  227): No valid device/modifier found with given identifier: \BC\B5
D/ALSADevice(  227): Device value returned is (null)
E/ALSADevice(  227): Failed to get pcm device node: (null)
E/AudioStreamInALSA(  227): read:: PCM device open failed
E/AudioFlinger(  227): read failed: framesRead=0
D/AudioStreamInALSA(  227): standby
D/ALSADevice(  227): standby: handle 0xb712f378 h 0x0
D/AudioStreamInALSA(  227): Checking for musbRecordingState 0
D/AudioHardwareALSA(  227): Closing USB Recording Session as no stream is active
D/AudioUsbALSA(  227): exitRecordingThread
D/AudioUsbALSA(  227): write to fd
D/AudioUsbALSA(  227): closeDevice handle 0x0
D/AudioUsbALSA(  227): closeDevice handle 0x0
W/MPEG4Writer(  227): 0-duration samples found: 1
W/MPEG4Writer(  227): 0-duration samples found: 1
I/MPEG4Writer(  227): Received total/0-length (0/0) buffers and encoded 0 frames. - Audio
I/MPEG4Writer(  227): Audio track drift time: 0 us
I/MediaCodecSource(  227): encoder (audio) stopped
I/MediaCodecSource(  227): puller (audio) stopping
D/AudioStreamInALSA(  227): standby
D/ALSADevice(  227): standby: handle 0xb712f378 h 0x0
D/AudioStreamInALSA(  227): Checking for musbRecordingState 0
D/AudioHardwareALSA(  227): Closing USB Recording Session as no stream is active
D/AudioUsbALSA(  227): exitRecordingThread
D/AudioUsbALSA(  227): write to fd
D/AudioUsbALSA(  227): closeDevice handle 0x0
D/AudioUsbALSA(  227): closeDevice handle 0x0
I/MediaCodecSource(  227): puller (audio) stopped
D/MPEG4Writer(  227): Audio track source stopped
D/MPEG4Writer(  227): Stopping writer thread
D/MPEG4Writer(  227): 0 chunks are written in the last batch
D/MPEG4Writer(  227): Writer thread stopped
D/MPEG4Writer(  227): Audio track stopping
E/MediaRecorder(10386): stop failed: -1007
E/Call recorder: (10386): RuntimeException
I/InCall  ( 9737): CallList - hasAnyLiveCall call = [Call_1, DISCONNECTING, [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MERGE_CONFERENCE CAPABILITY_MUTE], children:[], parent:null, videoState:0, mIsActivSub:false, callSubState:0, mSessionModificationState:0, conferenceable:[], VideoSettings:(CameraDir:-1)]
D/AudioStreamInALSA(  227): close
D/AudioStreamInALSA(  227): Deregistering REC bit, musbRecordingState:0
D/AudioStreamInALSA(  227): close
D/AudioHardwareALSA(  227): Closing USB Recording Session as no stream is active
D/AudioUsbALSA(  227): exitRecordingThread
D/AudioUsbALSA(  227): write to fd
D/AudioUsbALSA(  227): closeDevice handle 0x0
D/AudioUsbALSA(  227): closeDevice handle 0x0
D/ALSAStreamOps(  227): close
D/ALSAStreamOps(  227): close() : Found mHandle 0xb712f378, proceeding to close
D/ALSADevice(  227): close: handle 0xb712f378 h 0x0
D/ALSAStreamOps(  227): close
D/ALSAStreamOps(  227): close() : Found mHandle 0xb712f378, proceeding to close
D/ALSADevice(  227): close: handle 0xb712f378 h 0x0
W/AudioFlinger(  227): session id 171 not found for pid 10386
I/InCall  ( 9737): CallList - onDisconnect: [Call_1, DISCONNECTED, [Capabilities: CAPABILITY_HOLD CAPABILITY_SUPPORT_HOLD CAPABILITY_MERGE_CONFERENCE CAPABILITY_MUTE], children:[], parent:null, videoState:0, mIsActivSub:false, callSubState:0, mSessionModificationState:0, conferenceable:[], VideoSettings:(CameraDir:-1)]
I/InCall  ( 9737): InCallPresenter - Phone switching state: INCALL -> INCALL
D/Call recorder: (10386): RecordService deleteFile
D/Call recorder: (10386): FileHelper deleteFile /storage/emulated/0/recordedCalls/d20150511094619p1155.3gp
D/Call recorder: (10386): RecordService stopService
D/Call recorder: (10386): MyPhoneReciever phoneNumber null

**Comment by ghost** [comment]
Ok, works now! Sorry for my ignorance, looks like this feature first has to be enabled in the ROM!

**Comment by GreenLunar** [comment]
> Ok, works now! Sorry for my ignorance, looks like this feature first has to be enabled in the ROM!

Please, elaborate.

**Comment by ghost** [comment]
Well if you look a the changelog of Cyanogenmod, sometimes you'll find stuff like "Added call recording functionality for ***". This in combination with this call-recorder here, installed from the f-droid repository, suddenly working, made me come to that conclusion.

In the end it doesn't matter, as long as it works :)

**Comment by GreenLunar** [comment]
I will look into it.

Unfortunately, I do not have the budget to trouble myself with risks of bricking my devices by attempting to install sane ROMs.

By the way, please subscribe yourself to issue # 23

**Comment by GreenLunar** [comment]
By the way, please subscribe yourself to issue # 23
